title: Oscar Barajas Tavares
baseURL: https://gndx.dev/
languageCode: es-ES
params:
  description: Foundation Layer at @platzi - Microsoft MVP - Lead at Developer Circles from Facebook - I teach React & Svelte.
  color_scheme: dark
  accent_color: pink
  image: https://arepa.s3.amazonaws.com/og-gndx.png
  header:
    title: GNDX
    has_nav: true
    nav_links:
      - label: Inicio
        url: /
        style: link
      - label: Artículos
        url: /blog/
        style: link
      - label: Acerca
        url: /about/
        style: link
      - label: Cursos
        url: /cursos/
        style: link
      - label: Podcast
        url: https://open.spotify.com/show/0FmtewBzfG64SOilzlnDuK?si=8zxSmXbeRHSlBPE0oUw8Cg
        style: link
      - label: Discord
        url:  https://discord.gg/5mZc7fU5WZ
        style: link
  footer:
    content: >-
      Oscar Barajas Tavares @gndx | Todos los izquierdos reservados © 2021.
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/gndx'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - label: Instagram
        url: 'https://instagram.com/gndx'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - label: GitHub
        url: 'https://github.com/gndx/'
        style: icon
        icon_class: fa-github
        new_window: true
      - label: YouTube
        url: 'https://www.youtube.com/channel/UCw05fUBPwmpu-ehXFMqfdMw?sub_confirmation=1'
        style: icon
        icon_class: fa-youtube
        new_window: true
      - label: Twitch
        url: 'https://twitch.tv/gndxdev'
        style: icon
        icon_class: fa-twitch
        new_window: true
taxonomies:
  stub: stub
disableKinds:
  - taxonomy
  - taxonomyTerm